### ISSUE TITLE
Does this work at all?

### ISSUE THREAD

**Issue by BurntChip** [Jaycar-Electronics/Solar-MPPT-Charge-Controller#4]
This project appears to have many issues.
1.Your schematic shows an N-ch mosfet.
2.Strange gate gate drive circuit, why not use the BJT to ground the gate and turn the mosfet on.
3.No resistor at the base of the BJT = burnt arduino pin.
4.Pin D2 does not appear to be a PWM pin. Connection diagram shows D3.
5.At the standard PWM frequency, the inductor will saturate at duty cycle = 5.
6.Parts list, schematic and photos are inconsistant.
and more.

BC.

**Comment by Jaycar-Electronics** [comment]
1. Yes, this has been corrected, The error came from EAGLE software.
2. So there is not a large voltage swing on the gate; This actually comes as an improvement; as the BJT does not need to be connected to the `vin` source; it *is* at the moment, but it doesn't have to be.
3. Yes, resistor is missing from schematic, it usually fits under the nano. I've admended some images and text.
4. 3 it is; this has been fixed.
5. Can you confirm what you mean by this?

We appreciate kindly your contribution. The above errors have been fixed in the latest commit; If you have suggestions or improvements feel free to submit a pull request and we're happy to take a look at it;
